name: release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'The semver to use'
        required: true
        default: 'auto'
        type: choice
        options:
          - auto
          - patch
          - minor
          - major
          - prerelease
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    if: ${{github.event_name != 'pull_request' || (github.event.pull_request.merged && github.event.pull_request.user.login == 'optic-release-automation[bot]')}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: nearform-actions/optic-release-automation-action@9e3518763346efacba15d729d0faaa4cbd8fdd52 # v4.12.3
        with:
          commit-message: 'Release {version}'
          sync-semver-tags: false
          access: 'public'
          # This prefix is added before the prerelease number, e.g. `v3.0.0-alpha.0`
          # prerelease-prefix: 'alpha'
          semver: ${{ github.event.inputs.semver }}
          # Prereleases are published under the `alpha` npm dist-tag
          # npm-tag: ${{ startsWith(github.event.inputs.semver, 'pre') && 'alpha' || 'latest' }}
          # Don't notify linked issues
          notify-linked-issues: false
          publish-mode: oidc
          build-command: |
            npm ci --ignore-scripts
